CREATE TABLE ACCIDENTS
   (	"ID" NUMBER NOT NULL PRIMARY KEY, 
	"YEAR" NUMBER, 
	"MONTH" NUMBER, 
	"DAY" NUMBER, 
	"HOUR" NUMBER, 
	"MINUTE" NUMBER, 
	"LAT" NUMBER, 
	"LONGIT" NUMBER, 
	"VICTIMS" NUMBER
   ) 
